Restore webapp release and local prod
* Upgrade to Jetty 9.3.2.
* Rename log dirs to logs to be in sync with Jetty defaults.
* Fix Jetty 9.3's "DefaultServlet" mime type on .css.gz.
* Update Jetty settings, reduce differences from default.
* Serve HTTP/2.
* Jetty 9.3 deprecated GzipFilter in favour of GzipHandler.
* Stop webapp-server/grunt freezing.
* Local prod DB settings.

diff --git a/Release/webapp/install-war b/Release/webapp/install-war
--- a/Release/webapp/install-war
+++ b/Release/webapp/install-war
@@ -2,15 +2,15 @@
 
 cd "$(dirname "$0")"
 
-d=../../Code/webapp-server/target/scala-2.11/
+d=/tmp/shipreq.sbt/webapp-server/target/scala-2.11
+[ ! -e $d ] && echo "Directory not found: $d" && exit 1
 s="$(ls -1rt $d | fgrep .war | tail -1)"
 [ -z "$s" ] && echo "No WARs found in $d" && exit 1
-echo "Found: $s"
+echo "Found: $d/$s"
 
 echo "Installing..."
 cp -p $d/$s webapp/webapps/shipreq.war \
   && echo && ./war-compress_static_resources \
-  && echo && ./war-enable_gzip \
   && echo && ./war-force_https \
   && echo && echo "--------------------------------------------------------------------------------" \
   && ./war-inspect
