Fix Taskman healthcheck

diff --git a/Code/taskman-server/src/docker/bin/healthcheck b/Code/taskman-server/src/docker/bin/healthcheck
--- a/Code/taskman-server/src/docker/bin/healthcheck
+++ b/Code/taskman-server/src/docker/bin/healthcheck
@@ -1,10 +1,9 @@
 #!/bin/bash
-[ $# -ne 1 ] && echo "Usage: $0 <health file>" && exit 2
+[ $# -ne 2 ] && echo "Usage: $0 <health file> <max age>" && exit 2
 
-# find in alpine is limited.
-# -mmin 0 gives us "updated in the last minute" which is good enough
+[ ! -e "$1" ] && echo "File not found: $1" >&2 && exit 1
 
-d="$(dirname "$1")"
-f="$(basename "$1")"
-exec test -n "$(find "$d" -name "$f" -mmin 0)"
-
+age="$(( $(date +"%s") - $(stat -c "%Y" "$1") ))"
+echo "Age: $age"
+[ $age -gt "$2" ] && exit 1
+exit 0
